# Generated by Django 5.2.7 on 2025-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="receipts/%Y/%m/%d/"
            ),
        ),
    ]
