# Generated by Django 5.2.7 on 2025-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_receipt_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food & Dining", "Food & Dining"),
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Utilities", "Utilities"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
